JANA:MAX_RELAUNCH_THREADS 10
NTHREADS 8
PLUGINS monitoring_hists,ReactionFilter
JANA_CALIB_CONTEXT "variation=mc"
# pippim topology
Reaction0:Flags B4
Reaction0 1_14__8_9_14
# kpkm topology
Reaction1:Flags B4
Reaction1 1_14__11_12_14